### ISSUE TITLE
Part-1 開発モデル

### ISSUE THREAD

**Issue by IotaTech-Info** [IotaTech-Info/IotaJava_G3#4]
<img width="690" alt="article-image02-2" src="https://user-images.githubusercontent.com/69588837/146699573-cc927f87-a291-4b15-8809-9999b6053ee1.png">

**Comment by IotaTech-Info** [comment]
# ウォーターフォール型開発の詳細
![v-model-640x348](https://user-images.githubusercontent.com/69588837/146699447-e846459a-1ef0-4a26-9b4d-d1f50579fbd4.jpg)

**Comment by Takuu236** [comment]
[肖澤宇さんの自己紹介.txt](https://github.com/IotaTech-Info/IotaJava_G3/files/9468525/default.txt)
[EB履歴書_肖澤宇_20220830(最終版）.xlsx](https://github.com/IotaTech-Info/IotaJava_G3/files/9468526/EB._._20220830.xlsx)
